on:
  workflow_dispatch:

jobs:
  test_nim:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nim for work flow
        run: |
          sudo apt-get update
          sudo apt-get install nim
      - name: Test Nim
        shell: nim --eval:"cpFile(paramStr(3),\"x.nim\");selfExec\"c -r x.nim\"" skipper {0}
        run: |
          echo NimVersion
          echo currentSourcePath()
