on:
  workflow_dispatch:
  push:

jobs:
  test_nim:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nim for work flow on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install nim
      - name: Install Nim for work flow on Windows
        if: ${{ runner.os == 'Windows' }}
        #uses: crazy-max/ghaction-chocolatey@v3
        #with:
        #  args: install nim
        #
        # `refreshenv` updates PATH env variable so that you can call nim
        # Last command try to get the parent directory of installed Nim and add it to GITHUB_PATH
        # so that you can call nim in following `run`
        run: |
          choco install nim --no-progress
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          nim -v
          Add-Content $env:GITHUB_PATH (Get-Item((Get-Command nim).Path)).DirectoryName
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Build nimact
        run: nim c nimact/nimact.nim
      - name: Add nimact directory to the system PATH variable
        shell: bash
        run: echo "$PWD/nimact" >> "$GITHUB_PATH"
      - name: Test Nim
      #shell: nim --eval:"cpFile(paramStr(3),\"x.nim\");selfExec\"c -r x.nim\"" skipper {0}
        shell: nimact {0}
        run: |
          import std/[macros, sugar]

          dump CompileDate
          dump CompileTime
          dump NimVersion
          dump static getProjectPath()
          dump hostCPU
          dump hostOS
