on:
  workflow_dispatch:

jobs:
  test_nim:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nim for work flow on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install nim
      - name: Install Nim for work flow on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          choco install nim
      - name: Test Nim
        shell: nim --eval:"cpFile(paramStr(3),\"x.nim\");selfExec\"c -r x.nim\"" skipper {0}
        run: |
          import std/sugar

          dump CompileDate
          dump CompileTime
          dump NimVersion
          dump currentSourcePath()
          dump hostCPU
          dump hostOS
